version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Building test for $PROJECT
      - pip install pipenv
      - pipenv install --dev

  build:
    commands:
      - pipenv run python src/runner.py

artifacts:
  files:
    - $PROJECT/results/report.html
    - $PROJECT/results/log.html
    - $PROJECT/results/output.xml
