version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Building test for $PROJECT
      - export PYTHONPATH=$CODEBUILD_SRC_DIR/src:$PYTHONPATH
      - pip install pipenv
      - pipenv install --dev

  build:
    commands:
      - pipenv run robot --outputdir $PROJECT/results src/$PROJECT/tests/

artifacts:
  files:
    - $PROJECT/results/report.html
    - $PROJECT/results/log.html
    - $PROJECT/results/output.xml
